### ISSUE TITLE
Vanilla commands gone. [BUG]

### ISSUE THREAD

**Issue by TheDarkPreacher** [Ciprania/CipraTech#12]
**Describe the bug**
It seems that the commands for things in vanilla are gone, such as '/gamerule', possible interference from a mod.

**To Reproduce**
1: load pack
2: create new world with cheats enabled
3: try and use a command such as '/gamerule DoDaylightcycle false'

**Expected behavior**
Vanilla commands should work.

**Info (please complete the following information):**
 - Modpack Version: 0.0.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 0.0.1

**Additional context**
Possibly Ma Essentials causing the issue.

**Comment by Saphrym** [comment]
I was afraid something like that would happen. The "Ma" mods have not been reliable. This is fine. There is other teleportation in the pack, which was the main reason to have this mod in my eyes.

**Comment by Saphrym** [comment]
Can you try removing the mod and see if you still have the same issues? ToolKit also modifies commands.

**Comment by TheDarkPreacher** [comment]
Removed Ma Essentials, removed Toolkit... still having the same issue.

loaded up an instance with just the latest Forge. (31.1.1)

and only Forge.

Still having the issue.

It's Forge. Forge is removing access to the vanilla commands.

**Comment by Saphrym** [comment]
Ok. Thanks. I might keep Ma Essentials then for now.

**Comment by Saphrym** [comment]
Closing since it has been reported to Forge.
