### ISSUE TITLE
[MOD] Trash Slot

### ISSUE THREAD

**Issue by brujam** [Ciprania/CipraTech#13]
**Which mod?**
Trash Slot

**Mod link**
https://www.curseforge.com/minecraft/mc-mods/trashslot

**Why?**
QOL / Convenience mod for disposing of items.

**Before Submitting**
>Before submitting, make sure the mod you selected is a FORGE mod for 1.15.2. It needs to be available on CurseForge. It also should fit the nature of the pack, which is specifically a tech pack. Quality of life mods are also encouraged. Needs to be server friendly.
Is a Forge mod. Is on Curseforge. Is a QOL mod. Is probably server friendly, can't see how it wouldn't be.

>Also make sure it's not already in the [mod list](https://github.com/Ciprania/CipraTech/wiki/Mod-List).
Ctrl-F "Trash" found nothing.

**Comment by Saphrym** [comment]
Ma Essentials has a /trash command. :)
