### ISSUE TITLE
[MOD] Ultimate Car Mod

### ISSUE THREAD

**Issue by brujam** [Ciprania/CipraTech#14]
**Which mod?**
Ultimate Car Mod

**Mod link**
https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod

**Why?**
Ciprania's based around a city, it might be fun/interesting to have roads and cars.

**Before Submitting**
> Before submitting, make sure the mod you selected is a FORGE mod for 1.15.2. It needs to be available on CurseForge. It also should fit the nature of the pack, which is specifically a tech pack. Quality of life mods are also encouraged. Needs to be server friendly.

Listed as Game Version: Forge.
Available on Curseforge: Yes
Tech-pack appropriate: Yes
QOL: No
Server-friendly: No idea

> Also make sure it's not already in the [mod list](https://github.com/Ciprania/CipraTech/wiki/Mod-List).

Ctrl-F "Car" finds only Slice of Life Carrot.

**Comment by Saphrym** [comment]
We can try this one.
