### ISSUE TITLE
[MOD] Mr Crayfish's Vehicle Mod

### ISSUE THREAD

**Issue by brujam** [Ciprania/CipraTech#15]
**Which mod?**
Mr Crayfish's Vehicle Mod

**Mod link**
* https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-vehicle-mod
* Requires Obfuscate: https://www.curseforge.com/minecraft/mc-mods/obfuscate

**Why?**
Similar niche to the Ultimate Car mod.
Has seemingly some useful vehicles (screenshots contain a combine harvester planting seeds)
"In this mod you can find an assortment of vehicles that will help you explore, farm, transport, race, and even fly!"

**Before Submitting**
>Before submitting, make sure the mod you selected is a FORGE mod for 1.15.2. It needs to be available on CurseForge. It also should fit the nature of the pack, which is specifically a tech pack. Quality of life mods are also encouraged. Needs to be server friendly.

Gameversion listed as Forge.
Minecraft 1.15 version available (does not mention 1.15.2)
Vehicles are definitely tech-pack suitable I would think
QOL: has transport and farming vehicles
Server-friendly: no idea

> Also make sure it's not already in the [mod list](https://github.com/Ciprania/CipraTech/wiki/Mod-List).

Ctrl-F "vehicle" finds nothing

**Comment by Saphrym** [comment]
This one has never been very server friendly. Gonna veto this. :)
