### ISSUE TITLE
[MOD] Useful Hats

### ISSUE THREAD

**Issue by brujam** [Ciprania/CipraTech#16]
**Which mod?**
Useful Hats

**Mod link**
https://www.curseforge.com/minecraft/mc-mods/useful-hats

**Why?**
>Why do you think this should be added?

https://github.com/cech12/UsefulHats/wiki/Mining-Hat - the Mining Hat sounds like a better / less laggy way to do the "vision in dark places" that Miners Helmet (https://www.curseforge.com/minecraft/mc-mods/miners-helmet) does via Dynamic Lighting. I'd like a mod that allows for easier by-hand mining and the mining hat seems to fill that niche.
Also, the other hats seem to be really good too!

**Before Submitting**
> Before submitting, make sure the mod you selected is a FORGE mod for 1.15.2. It needs to be available on CurseForge. It also should fit the nature of the pack, which is specifically a tech pack. Quality of life mods are also encouraged. Needs to be server friendly.

Curseforge page does not mention Forge, however Wiki specifies Forge: https://github.com/cech12/UsefulHats/wiki
Version tag specifies 1.15.2.
Most hats are "normal" (wing helmet and halo are not, and appear magical). Based on comments, the helmets are disable-able individually.

>Also make sure it's not already in the [mod list](https://github.com/Ciprania/CipraTech/wiki/Mod-List).

Ctrl-F "hat" finds nothing.

**Comment by Saphrym** [comment]
We can try this one.
