### ISSUE TITLE
[MOD] Mr Crayfish's Furniture Mod

### ISSUE THREAD

**Issue by brujam** [Ciprania/CipraTech#17]
**Which mod?**
Mr Crayfish's Furniture Mod

**Mod link**
https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod

**Why?**
>Why do you think this should be added?

Adds a lot of modern-looking furniture. PCs, Printers, etc based on the Modern Update https://www.youtube.com/watch?v=zeogCR22aAM - would be good for building diners or similar buildings based on screen shots and youtube video. 

Finally, Mr Crayfish's Vehicle Mod mentions "Bonus vehicles when installed with MrCrayfish's Furniture Mod".

**Before Submitting**
>Before submitting, make sure the mod you selected is a FORGE mod for 1.15.2. It needs to be available on CurseForge. It also should fit the nature of the pack, which is specifically a tech pack. Quality of life mods are also encouraged. Needs to be server friendly.

Forge: Yes.
1.15.2: https://mrcrayfish.com/mods?id=cfm#downloads suggests it's for 1.15.1. :( I don't know if these are cross-compatible.
Available on Curseforge: Yes.
Tech nature: yes. Modern update has many modern-/tech-themed decorations and furniture.
QOL: Insofar as it is pretty storage/props, yes?
Server-friendly: Can't see why it wouldn't be.

>Also make sure it's not already in the [mod list](https://github.com/Ciprania/CipraTech/wiki/Mod-List).

Ctrl-f "furniture" finds mcw-furniture which is https://www.curseforge.com/minecraft/mc-mods/macaws-furniture - Macaws Furniture.
We can have more than one, I'd assume :)

**Comment by brujam** [comment]
Also has US-style mailboxes - and description mentions it's a fully-working mail system. Could be a reasonable replacement for "shared ender chests" or similar.

**Comment by brujam** [comment]
Twitch client does not show this as installable for 1.15.2. Closing.

**Comment by Saphrym** [comment]
Going to reopen this. For the story I'm going with, it makes sense.
