### ISSUE TITLE
[SUGGESTIONS] Stuff found during 2/10/2020 stream

### ISSUE THREAD

**Issue by TheDarkPreacher** [Ciprania/CipraTech#18]
Copper ore doubled up (Silent's Mechanisms and Mekanism)
Tin ore doubled up (see previous)
Remove DefaultAmplified mod (laggy)
Remove InventoryHud mod (buggy)

**Comment by TheDarkPreacher** [comment]
Further Suggestions:
Change config for Campfire torches (1 stick = 1 torch currently) Possibly increase, 1 stick = 2 torches?
Add CT recipe for sticks from Citrus Planks
Check config for Engineer's tools, possibly add other seed types to use with the power bar press (beet root, canola, etc.) and possibly tweak amount of saturation a bar gives?
add CT recipe for wheat to seeds.
CT recipe for 8 logs = 4 chests, 2 logs = 16 sticks.

**Comment by Saphrym** [comment]
Citrus planks work in my current version.
I can't find a config for campfire torches. Let me know the name of the file if you find it.
I don't see configs for the power bar or the press.

Added wheat to seeds recipe.
Added logs to chests recipe.
Added Logs to sticks recipe.
