### ISSUE TITLE
[BUG] Very high TPS and lag spikes in singleplayer

### ISSUE THREAD

**Issue by TheDarkPreacher** [Ciprania/CipraTech#19]
**Describe the bug**
Occasionally, there is a large TPS spike and even lag in singleplayer, causing blocks to reappear if broken, tile entities to not open if interacted with, or rubberbanding when travelling

**To Reproduce**
1: Start up pack
2: play for a while normally
3: try and open a chest or furnace, or break a block

**Expected behavior**
No TPS or lag spikes

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 0.0.2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 0.0.2

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
I decided to test a few things, ran the `/forge entity list` command, and the count of minecraft:item was fairly high (30-40). Disabled the Dye It Yourself mod, started the game again, and the TPS problems and lag was lessened. Another possible issue could be Peaceful Surface doing a lot of calculations and spawn searching in areas with Lost Cities cities near the player. Will do more testing without Peaceful Surface and add to this report.

**Comment by TheDarkPreacher** [comment]
Further testing: killing the sheep in the area also improves performance, and if a city from Lost Cities is nearby and not lit up, still some performance hits. Lighting up the buildings in the city helps, since it lowers spaces that Peaceful Surface has to calculate. Possible solutions: Change config for both Peaceful Surface and Dye It Yourself to increase time between dye drops, and to restrict spawns to certain altitudes, i.e., lower than y:60.

**Comment by Saphrym** [comment]
Configs don't seem to work to fix the issues. Removing mods since they would probably make a server suffer over time.
