### ISSUE TITLE
[CFG] Campfire Torches via CT Script

### ISSUE THREAD

**Issue by TheDarkPreacher** [Ciprania/CipraTech#22]
**Which mod?**
CraftTweaker

**Config File**
Ciprania.zs

**Config Change**
campfire + 1 stick = 3 torches

**Code**
`campfire.addRecipe("torches", <item:minecraft:torch> * 3, <item:minecraft:stick>, 1.0, 100);`

//Note:
With this script, you can change the "* 3" to either 2 or 4 or whatever, and it works. Plus, one less mod!

**Comment by Saphrym** [comment]
What does the 1.0 and 100 do?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheDarkPreacher** [comment]
1.0 is the XP drop and 100 is cook time.
