### ISSUE TITLE
[DOC] Ultimate Car Mod Wiki info

### ISSUE THREAD

**Issue by TheDarkPreacher** [Ciprania/CipraTech#24]
**What documentation would you like added or changed?**
Ultimate Car mod is not intuitive even with JEI, so maybe some wiki info added in would help

//Main Wiki Page with links to other pages.
https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod/pages/overview
Quick start and Fuel production info would be helpful.

**Comment by Saphrym** [comment]
Because it's removed.... closing.
