### ISSUE TITLE
PreFab

### ISSUE THREAD

**Issue by RedCharpie** [Ciprania/CipraTech#26]
**Which mod?**
Prefab

**Mod link**
https://www.curseforge.com/minecraft/mc-mods/prefab

**Why?**
Because I am Charpie and you heart me. Also, I think the modpack is pretty neat pack. I guess you can say that it is a quality of life pack for. You gather resources that create blueprints for structures such as a house, warehouse, farm, barn and so on.  

**Before Submitting**
Before submitting, make sure the mod you selected is a FORGE mod for 1.15.2. It needs to be available on CurseForge. It also should fit the nature of the pack, which is specifically a tech pack. Quality of life mods are also encouraged. Needs to be server friendly.

Also make sure it's not already in the [mod list](https://github.com/Ciprania/CipraTech/wiki/Mod-List).

**Comment by Saphrym** [comment]
Approved and added to 0.0.5
