### ISSUE TITLE
[BUG] Recipe conflict between More Charcoal and XL Food

### ISSUE THREAD

**Issue by TheDarkPreacher** [Ciprania/CipraTech#27]
**Describe the bug**
When cooking eggs in furnace, you get egg charcoal, not fried egg.

**To Reproduce**
smelt an egg in a furnace

**Expected behavior**
Expected to get a fried egg, not charcoal

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 1.0.0
 - Server or Singleplayer: Server
 - Version the world was created on: 1.0.0

**Additional context**
Changing out More Charcoal for a different mod that makes coal and charcoal pieces will remove the conflict. Suggested replacement: MiniCoal (https://www.curseforge.com/minecraft/mc-mods/minicoal)

**Comment by brujam** [comment]
Alternately - remove the Fried Egg recipe from the furnace and add it to the vanilla Smoker
Alternately - remove the Egg Charcoal recipe from the furnace and add it to the vanilla Blast Furnace

**Comment by Saphrym** [comment]
Removed.
