### ISSUE TITLE
[BUG] Can't Hit mobs (Swing Thru Grass)

### ISSUE THREAD

**Issue by TheDarkPreacher** [Ciprania/CipraTech#28]
**Describe the bug**
players on servers have issues hitting mobs

**To Reproduce**
have the mod on a server, have multiple players join, have them attack mobs.

**Expected behavior**
players should be able to hit mobs.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 1.0.0
 - Server or Singleplayer: server
 - Version the world was created on: 1.0.0

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
Swing Thru Grass causes an issue with players on servers. Suggest removing it for next update.

**Comment by Saphrym** [comment]
Removed.
