### ISSUE TITLE
[CFG] Silent's Gems Corrupted slimes and 

### ISSUE THREAD

**Issue by TheDarkPreacher** [Ciprania/CipraTech#30]
**Which mod?**
Silent's Gems
Crafttweaker

**Config File**
silentgems-common.toml
Ciprania.zs

**Config Change**
Set config for corrupted slimes to false
Add recipe for water wisp essence to CT Script since wisps are off and the essence is needed for a token enchant.

**Code**
Slimes:
`#Spawn a group of corrupted slimes
		"silentgems:corrupted_slimes" = false`
Water wisp essence:
(will have to decide on CT Script later)

**Before Submitting**
Check and make sure that the config change is not already there. Keep it server friendly.

**Comment by Saphrym** [comment]
Removed slimes and fire producing events.
