### ISSUE TITLE
[CFG] Fuelium Fix datapack

### ISSUE THREAD

**Issue by TheDarkPreacher** [Ciprania/CipraTech#33]
**Which mod?**
Mekanism and MrCrayfish's Vehicle Mod.

**Config File**
datapack to go into The Loader datapack folder

**Config Change**
This makes it so we can make fuelium for the vehicles using Mekanism Ethylene

**Code**
Download ZIP file, add to folder: https://drive.google.com/open?id=1d4pdzr-cQHYisQrlMRjBph6jVyuDVk-K

**Comment by Saphrym** [comment]
Added.
