### ISSUE TITLE
[CFG] Find a replacement for the wisp drops for Silent's

### ISSUE THREAD

**Issue by Saphrym** [Ciprania/CipraTech#37]
From Preach:

"Ok, since wisps are disabled and wisp essence is needed for a few things (enchanting tokens, a couple runes) I have come up with some suggestions for alternative recipes to make the essences.

Chaos recipe: 4 chaos shards around chaos coal in crafting table
Fire recipe: Soul gem of cave spider or rabbit (alternative: fire charge surrounded by chaos shards)
water recipe: soul gem of pufferfish or wither skellie (alternative: cod surrounded by chaos shards)
ice recipe: soul gem of drowned or cow (alternative: blue ice surrounded by chaos shards)
lightning recipe: soul gem of pig or skellie (alternative: grave's dust surrounded by chaos shards)

Let me know if some of this sounds good and I'll try and write up some scripts for that as well. I also might have some wisp essence textures we can use for a resource pack instead of the "to do" textures."

**Comment by TheDarkPreacher** [comment]
`//Wisp VooDoo
craftingTable.addShaped("waterwisp", <item:silentgems:water_wisp_essence>, [[<item:minecraft:bone_meal>, <item:minecraft:cooked_chicken>, <item:minecraft:gravel>]]);
craftingTable.addShaped("chaoswisp", <item:silentgems:chaos_wisp_essence>, [[<item:silentgems:chaos_crystal_shard>, <item:minecraft:cooked_chicken>, <item:minecraft:gravel>]]);
craftingTable.addShaped("firewisp", <item:silentgems:fire_wisp_essence>, [[<item:minecraft:gunpowder>, <item:minecraft:cooked_chicken>, <item:minecraft:gravel>]]);
craftingTable.addShaped("icewisp", <item:silentgems:ice_wisp_essence>, [[<item:minecraft:snowball>, <item:minecraft:cooked_chicken>, <item:minecraft:gravel>]]);
craftingTable.addShaped("lightningwisp", <item:silentgems:lightning_wisp_essence>, [[<item:minecraft:redstone>, <item:minecraft:cooked_chicken>, <item:minecraft:gravel>]]);`

**Comment by Saphrym** [comment]
Added with a slight change.
