### ISSUE TITLE
[BUG] Recipe Conflict: Pile of Bricks/Block of Brick

### ISSUE THREAD

**Issue by Saphrym** [Ciprania/CipraTech#38]
Ferg:

I did find a recipe conflict with the prefab you can't make the pile of bricks it just makes a block of brick  from JAOPCA which the recipe doesn't register for prefab.

**Comment by TheDarkPreacher** [comment]
`//Pile Of Bricks
craftingTable.removeRecipe(<item:jaopca:storage_blocks.brick>);
craftingTable.addShaped("compressedbrick", <item:jaopca:storage_blocks.brick>, [[<item:minecraft:bricks>, <item:minecraft:bricks>], [<item:minecraft:bricks>, <item:minecraft:bricks>]]);
craftingTable.addShapeless("uncompressedbrick", <item:minecraft:bricks> * 4, [<item:jaopca:storage_blocks.brick>]);`

**Comment by Saphrym** [comment]
Added
