### ISSUE TITLE
XL Salt [BUG]

### ISSUE THREAD

**Issue by FoxBotGames** [Ciprania/CipraTech#40]
**Describe the bug**
Water bucket to salt in smoker does not return bucket
**To Reproduce**
Place water bucket in smoker with fuel
**Expected behavior**
To get a bucket back after salt item has been crafted

**Info (please complete the following information):**
 - Modpack Version: 1.0.0
 - Server or Singleplayer: Both
 - Version the world was created on: 1.0.0

**Suggested Fixes or Alternatives**
I offer the idea of adding a salt tag, there are several different options for salt and they all have their own mods and applications that would be useful to have the ability to use more globally.

**Comment by FoxBotGames** [comment]
Brought to my attention there already is several salt tags. I have no idea how to fix the issue above.
Additional issues caused BY salt:
Mechanism's Salt does not craft food from XL Foods mod. I believe it has something to do with the mod itself and not tags.

**Comment by Saphrym** [comment]
Fixed.
