### ISSUE TITLE
[MOD] Decorative Blocks

### ISSUE THREAD

**Issue by TheDarkPreacher** [Ciprania/CipraTech#42]
**Which mod?**
Decorative Blocks

**Mod link**
https://www.curseforge.com/minecraft/mc-mods/decorative-blocks

**Why?**
adds in some decorative blocks that would go well with a Barlock build.

**Comment by Saphrym** [comment]
Added to test locally.

**Comment by Saphrym** [comment]
There are glitches with rendering, such as the iron bars showing an xray of the world below. Since it was an McCreator mod, I'm gonna have to let this one simmer for a while. For now, it's a no. :(
