### ISSUE TITLE
Rice to Slime [CFG] 

### ISSUE THREAD

**Issue by FoxBotGames** [Ciprania/CipraTech#43]
Since there is no "Rice Slime" item from any of the mods available. I offer the suggestion of crafting 3 "raw" rice from XL Foods and a bucket of water to produce one slime ball. The recipe doesn't have to be that. It would just be nice to not have to roam around for a mental year to find a slime chunk or swamp that you only "might" get slimes from

**Comment by Saphrym** [comment]
Added to dev version.

`//Add protoslime tag
<tag:cipratech:protoslime>.createItemTag();
<tag:cipratech:protoslime>.addItems([<item:xlfoodmod:rice>,<item:xlfoodmod:tomato>,<item:minecraft:egg>]);

//craft slime using 4 protosliime ingredients
craftingTable.addShapeless("slime_from_food", <item:minecraft:slime_ball>,
  [<tag:cipratech:protoslime>, <tag:cipratech:protoslime>, <tag:cipratech:protoslime>, <tag:cipratech:protoslime>],null);`
