### ISSUE TITLE
Empty Tag forge:fillet_knife [BUG]

### ISSUE THREAD

**Issue by Ranzer1255** [Ciprania/CipraTech#45]
**Describe the bug**
empty Tag on crafting recipe for Raw Fish Fillet

**Screenshots**
![image](https://user-images.githubusercontent.com/5742529/75204894-cfd6cc80-5737-11ea-9b6f-8cc120503277.png)

**Info (please complete the following information):**
 - Modpack Version: 1.0.1
 - Server or Singleplayer: server
 - Version the world was created on: 1.0.0

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by Saphrym** [comment]
Server reload fixed the issue.
