### ISSUE TITLE
Ankh of Pray [BUG]

### ISSUE THREAD

**Issue by FoxBotGames** [Ciprania/CipraTech#47]
**Describe the bug**
Ankh of Pray from Corail Tombstone has a 3 hour timer as to how frequently you can use it to "pray" (over decorative tombstones). If you log out this timer RESETS. This was NOT an issue in 1.0.0
**To Reproduce**
Use Ankh of Pray over a decorative grave, wait and record time on Ankh, log out and back in, find timer has reset.
**Expected behavior**
Log out and back in to the same time on the timer.

**Info:**
 - Modpack Version: 1.0.1
 - Server or Singleplayer: Server
 - Version the world was created on: 1.0.0

**Additional context**
Was not an issue in 1.0.0 
Was there an update for that mod between pack versions? Is there one available now?
   If so: Is the issue already fixed?
   If not: Is there already a bug report for this issue?

**Comment by Saphrym** [comment]
If you check the changelog, there was no update to Corail. There is for the next version. Feel free to find out if it works with the next version. I don't see how it would have changed between 1.0.0 and 1.0.1

**Comment by FoxBotGames** [comment]
After more testing (since the timer is 3 HOURS I have had to take some time) it is an issue with the way the Corail Tombstone mod's timer for the Ankh of Pray is handled when placed in alternate inventory options (Like a Dank cube or a backpack). My next test is how it handles in just a vanilla item chest.
After that is to update the mod (to another save) and test from there.

**Comment by Saphrym** [comment]
Definitely sounds like a bug to mention at their GitHub.  Thanks for testing. I'll close this for now since it's not really a modpack bug.
