### ISSUE TITLE
[CFG] Silent's Uranium to Powah's Uraninite

### ISSUE THREAD

**Issue by jengeld4** [Ciprania/CipraTech#51]
**Which mod?**
Which mod are we doing configs for?
Powah!
**Config File**
What is the file name of the config file to change?
Based on Powah's Github, create:
Powah/src/main/resources/data/powah/recipes/crafting/uraninite_raw_dense_from_urananite.json
**Config Change**
Describe the change. What does it accomplish?
Saphrym already proposed this change, and I agree with it. As it stands, Silent's Uranium has no purpose. A shapeless crafting recipe like this one can convert it to something useful, however, other uraninite results may also work.
**Code**
Provide the code required to make the change

{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
"item": "silents_mechanisms:uranium_ingot"
  ],
  "result": {
	"item": "powah:uraninite_raw_dense"
  }
}

**Before Submitting**
Check and make sure that the config change is not already there. Keep it server friendly.

**Comment by Saphrym** [comment]
I may just tag uranium as uraninite. So it can be used that way.
