### ISSUE TITLE
add mod interlink recipe (Alchemestry <-> Industrial Forgoing) [CFG] 

### ISSUE THREAD

**Issue by Ranzer1255** [Ciprania/CipraTech#54]
alternate way to craft Plastic form Industrial forgoing

add recipe to go from PolyVinyl Chloride in Alchemestry to Plastic.

balance cost as you see fit :D

**Comment by Saphrym** [comment]
Suggested code? Or recipe? :P

**Comment by Ranzer1255** [comment]
Spent most the day playing with CT script integration for alchemesty but my PC at work wasn't cooperating. Will try some more tonight. I think the CT script examples I was following were based on 1.12.2 not 1.15

Mostly I'm thinking 16 PVC to one plastic (same ratio the ingots in alchemesty uses) 

If I cant get integration with the chemical combiner working we can add a shapeless Crafting recipe of 9 PVC to one plastic
