### ISSUE TITLE
[BUG] RS: invalid recipe

### ISSUE THREAD

**Issue by jengeld4** [Ciprania/CipraTech#57]
**Describe the bug**
Refined storage doesn't seem to like the new food->slime recipes. At the time I'm writing this, I tried making a pattern with 4 rice to one slime. The pattern is created, and works, but Refined storage label says the recipe is invalid.
**To Reproduce**
Create a proto-slime pattern. Processing off, Exact off or on, doesn't matter
**Expected behavior**
Ideally, the patter should behave like the others, but even if it gives the proper name on mouse over, it might save some confusion.
**Screenshots**
[https://gyazo.com/ff733ee0097b3a11144e9eae6ded1c30](url)
**Info (please complete the following information):**
 - Modpack Version: 1.02
 - Server or Singleplayer: server
 - Version the world was created on: Unknown (likely 1.0?)

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.
I notice that the slime recipe doesn't correctly show which food can be used in JEI. So far, I noticed that eggs, rice and tomatos are shown, but they don't rotate, instead I notice that each of those recipes seems to cycle when I log in, and then stays that recipe until I log out. Might have something to do with it.

**Comment by Saphrym** [comment]
I believe this is CraftTweaker causing the issue. Not much I can do until it is fixed by the developer. Closing for now. Feel free to reply if you have ideas.

**Comment by Saphrym** [comment]
Fixed in 1.0.3
