### ISSUE TITLE
[MOD] Acceleratorcraft

### ISSUE THREAD

**Issue by brujam** [Ciprania/CipraTech#7]
**Which mod?**
Acceleratorcraft

**Mod link**
https://www.curseforge.com/minecraft/mc-mods/acceleratorcraft

**Why?**
Has some basic farmland automation, and fishing automation.

**Before Submitting**
>Before submitting, make sure the mod you selected is a FORGE mod for 1.15.2. It needs to be available on CurseForge. It also should fit the nature of the pack, which is specifically a tech pack. Quality of life mods are also encouraged.

* Exists in TNP Limitless 2 which is a 1.15.2 Forge pack

**Comment by Saphrym** [comment]
I won't be adding tick accelerators to the pack. They are not server friendly. Thanks for the suggestion though.
