### ISSUE TITLE
[MOD] Aquaculture

### ISSUE THREAD

**Issue by brujam** [Ciprania/CipraTech#8]
**Which mod?**
Aquaculture

**Mod link**
https://www.curseforge.com/minecraft/mc-mods/aquaculture

**Why?**
Better fishing, more loot from fishing, some neat armour and tools for getting started.

**Before Submitting**
>Before submitting, make sure the mod you selected is a FORGE mod for 1.15.2. It needs to be available on CurseForge. It also should fit the nature of the pack, which is specifically a tech pack. Quality of life mods are also encouraged.

Exists in TNP Limitless 2 which is a Forge 1.15.2 mod.
Not specifically a magic mod (though references to Neptune on tools and armour may disqualify it as such).
More interesting fishing and food acquisition (fish filleting).

**Comment by Saphrym** [comment]
This is already in the pack. :)
